// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTUEULkrxLp97bPGuDRhyguoYyF9V63w',
    appId: '1:191849100523:web:4395fb7c8f8ccd7b7e7aae',
    messagingSenderId: '191849100523',
    projectId: 'atelier4-badr-ibzazne-iir5g6',
    authDomain: 'atelier4-badr-ibzazne-iir5g6.firebaseapp.com',
    storageBucket: 'atelier4-badr-ibzazne-iir5g6.appspot.com',
    measurementId: 'G-LF0BK8GY9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVw4B8UY-lSo5S_59LKu6fRlV4GsgGvMk',
    appId: '1:191849100523:android:b9f5ccab38969f897e7aae',
    messagingSenderId: '191849100523',
    projectId: 'atelier4-badr-ibzazne-iir5g6',
    storageBucket: 'atelier4-badr-ibzazne-iir5g6.appspot.com',
  );
}
